name: kflavor
description: "kflavor automates flutter multi-flavor configuration for android, iOS and web, managing firebase settings, icons, splash screens, gradle/xcode config, and IDE run/debug profiles."
version: 1.1.2
homepage: https://kflavor.iamyash.in/
repository: https://github.com/yashpatel2202/kflavor
issue_tracker: https://github.com/yashpatel2202/kflavor/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

executables:
  kflavor: kflavor

dependencies:
  flutter:
    sdk: flutter
  args: ^2.7.0
  yaml: ^3.1.3
  logging: ^1.3.0
  ansi_styles: ^0.3.2+1
  xml: ^6.6.1
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.10.5
  recase: ^4.1.0
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
