name: kflavor
description: "Flutter flavor setup plugin."
version: 0.0.1
homepage: https://iamyash.in

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

executables:
  kflavor: kflavor

dependencies:
  flutter:
    sdk: flutter
  args: ^2.7.0
  yaml: ^3.1.3
  logging: ^1.3.0
  ansi_styles: ^0.3.2+1
  xml: ^6.6.1
  flutter_launcher_icons: ^0.14.4
  recase: ^4.1.0
  build_runner: ^2.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0